# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				zombie_horse = true
				panda = true
				axolotl = true
				bee = true
				egg = true
				arrow = true
				cow = true
				magma_cube = true
				pig = true
				skeleton = true
				llama = true
				bat = true
				frog = true
				husk = true
				hoglin = true
				camel = true
				rabbit = true
				firework_rocket = true
				silverfish = true
				armor_stand = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				stray = true
				turtle = true
				shulker = true
				salmon = true
				wither_skeleton = true
				vex = true
				wandering_trader = true
				piglin_brute = true
				goat = true
				ocelot = true
				item_frame = true
				horse = true
				vindicator = true
				phantom = true
				minecart = true
				ender_dragon = true
				evoker = true
				mooshroom = true
				llama_spit = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				snowball = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true
				dragon_fireball = true
				chicken = true
				trader_llama = true
				donkey = true
				tropical_fish = true
				chest_minecart = true
				fox = true
				slime = true
				pillager = true
				iron_golem = true
				area_effect_cloud = true
				zombified_piglin = true
				blaze = true
				piglin = true
				cat = true
				zombie = true
				guardian = true
				ghast = true
				sheep = true
				fireball = true
				player = true
				pufferfish = true
				illusioner = true
				potion = true
				trident = true
				wither_skull = true
				eye_of_ender = true
				wolf = true
				villager = true
				skeleton_horse = true
				fishing_bobber = true
				tnt_minecart = true
				zombie_villager = true
				elder_guardian = true
				small_fireball = true
				boat = true
				strider = true
				polar_bear = true
				painting = true
				cave_spider = true
				witch = true
				cod = true
				spider = true

			[light_sources.settings.entities.bewitchment]
				werewolf = true
				raven = true
				owl = true
				herne = true
				horned_spear = true
				toad = true
				snake = true
				lilith = true
				juniper_broom = true
				leonard = true
				ghost = true
				vampire = true
				baphomet = true
				hellhound = true
				demon = true

			[light_sources.settings.entities.dimdoors]
				monolith = true

			[light_sources.settings.entities.endermanoverhaul]
				savanna_enderman = true
				ice_spikes_enderman = true
				desert_enderman = true
				flower_fields_enderman = true
				windswept_hills_enderman = true
				ender_bullet = true
				coral_enderman = true
				spirit = true
				end_enderman = true
				corrupted_pearl = true
				nether_wastes_enderman = true
				mushroom_fields_enderman = true
				crimson_forest_enderman = true
				cave_enderman = true
				snowy_enderman = true
				dark_oak_enderman = true
				soulsand_valley_enderman = true
				crimson_pearl = true
				scarab = true
				end_islands_enderman = true
				swamp_enderman = true
				warped_forest_enderman = true
				badlands_enderman = true

			[light_sources.settings.entities.mca]
				male_zombie_villager = true
				female_zombie_villager = true
				female_villager = true
				male_villager = true

			[light_sources.settings.entities.lootr]
				lootr_minecart = true

			[light_sources.settings.entities.bosses_of_mass_destruction]
				blue_fireball = true
				lich = true
				obsidilith = true
				charged_ender_pearl = true
				comet = true
				gauntlet = true
				void_blossom = true

			[light_sources.settings.entities.naturalist]
				deer = true
				snail = true
				alligator = true
				rhino = true
				bluejay = true
				snake = true
				catfish = true
				boar = true
				caterpillar = true
				robin = true
				dragonfly = true
				duck_egg = true
				tortoise = true
				duck = true
				butterfly = true
				bear = true
				sparrow = true
				lizard = true
				rattlesnake = true
				zebra = true
				canary = true
				firefly = true
				hippo = true
				coral_snake = true
				cardinal = true
				lion = true
				vulture = true
				bass = true
				giraffe = true
				lizard_tail = true
				elephant = true
				finch = true

			[light_sources.settings.entities.mythicmounts]
				netherbat = true
				ridinglizard = true
				firebird = true
				courierbird = true
				moth = true
				nudibranch = true
				direwolf = true
				dragon = true
				griffon = true
				geckotoalizard = true
				acencia = true
				colelytra = true

			[light_sources.settings.entities.minecells]
				grenadier = true
				undead_archer = true
				shieldbearer = true
				leaping_zombie = true

			[light_sources.settings.entities.origins]
				enderian_pearl = true

			[light_sources.settings.entities.create]
				stationary_contraption = true
				super_glue = true

			[light_sources.settings.entities.betterend]
				dragonfly = true
				silk_moth = true

			[light_sources.settings.entities.terraform]
				boat = true

			[light_sources.settings.entities.scriptor]
				colorful_sheep = true

			[light_sources.settings.entities.aquamirae]
				anglerfish = true
				tortured_soul = true
				maw = true
				golden_moth = true
				maze_mother = true
				spinefish = true

			[light_sources.settings.entities.dungeonnowloading]
				spawner_carrier = true
				chaos_spawner = true
				great_experience_bottle = true
				hollow = true

			[light_sources.settings.entities.artifacts]
				mimic = true

			[light_sources.settings.entities.ad_astra]
				tier_1_rocket = true
				corrupted_lunarian = true
				lunarian = true
				star_crawler = true
				tier_4_rocket = true
				lander = true

